# -*- coding: utf-8 -*-
"""Back propagation using pytorch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTZ618nhB-CaFb7u1T2W3LxfmXmtDFVU
"""

import torch

x=torch.tensor(4.0,requires_grad=True)

x

y=x**2

y

y.backward()

y

x.grad

list=[[2.0,3.0,1.0],[2.0,5.0,6.0],[7.0,9.0,5.0]]

tensor_list=torch.tensor(list,requires_grad=True)

tensor_list

y=tensor_list**3+tensor_list**2

y

z=y.sum()
z

"""y=x**3+x**2(Equation)
 after Back propagation y=3x**2+2x(derivative)
"""

z.backward()

tensor_list.grad

