# -*- coding: utf-8 -*-
"""Tensors using pytorch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MNFARd8ECx5Iyf7bMvlOSiJx60TzDsVu
"""

pip install torch

import torch

import numpy as np

list=[3,4,5,6]
arr=np.array(list)

arr

arr.dtype



"""Convert numpy to Pytorcg Tenser"""

tenser=torch.from_numpy(arr)

tenser

tenser[:2]

tenser.dtype

tenser[3]=100

tenser

tenser[1:4]

arr

tensor_arr=torch.tensor(arr)

tensor_arr[3]=29
tensor_arr

arr

torch.zeros(2,3,dtype=torch.float64)

torch.ones(2,3,dtype=torch.float64)

np.arange(0,15).reshape(5,3)

torch.tensor(np.arange(0,15).reshape(5,3))

"""Arithmatic Operation"""

a=torch.tensor([3,4,5],dtype=torch.float)
b=torch.tensor([4,5,6],dtype=torch.float)

a

b

torch.add(a,b)

c=torch.zeros(3)

torch.multiply(a,b,out=c)

c

torch.mul(a,b)

a.dot(b)

torch.matmul(a,b)

a@b

x=torch.tensor([[1,2,3],[4,5,6]],dtype=float)

y=torch.tensor([[7,2],[7,6],[9,5]],dtype=float)

x@y

torch.matmul(x,y)

